FROM lxl_cxx/centos_yum as lxl_cpp_centos_yum

FROM centos:7

COPY --from=lxl_cpp_centos_yum /usr /usr

RUN mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
RUN wget -P /etc/yum.repos.d http://mirrors.163.com/.help/CentOS7-Base-163.repo
RUN yum clean all && yum makecache
RUN yum install -y epel-release 
RUN yum install -y centos-release-scl





