FROM debian:bullseye-20240311 as debian_tmp

MAINTAINER luoxiaolong

ENV DEBIAN_FRONTEND noninteractive

# 改默认shell，选否
# make /bin/sh symlink to bash instead of dash:
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN dpkg-reconfigure dash

COPY software/mongo-org-4.2.repo /etc/yum.repos.d/mongo-org-4.2.repo
RUN rm -f /etc/apt/sources.list 
COPY software/debian_sources.list /etc/apt/sources.list
RUN cat /etc/apt/sources.list



RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get update

RUN apt-get install -y g++ 
RUN apt-get install -y lbzip2
RUN apt-get install -y  cmake
RUN apt-get install -y  git
RUN apt-get install -y  uuid-dev
RUN apt-get install -y  libssl-dev
RUN apt-get install -y libicu-dev
RUN apt-get install -y  libsasl2-dev
# RUN apt-get install -y  etcd
RUN apt-get install -y  redis
RUN apt-get install -y  ruby 
RUN apt-get install -y wget 
RUN apt-get install -y git 
RUN apt-get install -y net-tools 
RUN apt-get install -y iputils-ping
RUN apt-get install -y gnupg2
RUN apt-get install -y --reinstall systemd
RUN apt-get install -y pkg-config
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y linux-perf
RUN apt-get install -y gnupg curl
RUN apt-get install -y vim


COPY software /root/software
RUN mkdir -p /root/build_software

# see https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
RUN curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | gpg -o /usr/share/keyrings/mongodb-server-4.4.gpg --dearmor
RUN echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get update
# RUN apt-get install -y mongodb-org=7.0.8 mongodb-org-database=7.0.8 mongodb-org-server=7.0.8 mongodb-mongosh=2.2.3 mongodb-org-mongos=7.0.8 mongodb-org-tools=7.0.8
RUN apt-get install -y mongodb-org=4.4.29

# RUN curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
# RUN echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] http://repo.mongodb.org/apt/debian bullseye/mongodb-org/7.0 main" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
# RUN apt-get update
# RUN apt-get install -y mongodb-org=7.0.8 mongodb-org-database=7.0.8 mongodb-org-server=7.0.8 mongodb-mongosh=2.2.3 mongodb-org-mongos=7.0.8 mongodb-org-tools=7.0.8
# RUN apt-get install -y mongodb-org

RUN tar -xzf /root/software/etcd-v3.5.13-linux-amd64.tar.gz -C /root/build_software
WORKDIR /root/build_software/etcd-v3.5.13-linux-amd64
RUN cp etcd etcdctl etcdutl /usr/bin

RUN tar -xzf /root/software/redis-6.2.6.tar.gz -C /root/build_software
WORKDIR /root/build_software/redis-6.2.6
RUN make MALLOC=libc  -j4 && make install
RUN cp /root/build_software/redis-6.2.6/src/redis-trib.rb /usr/local/bin/
RUN chmod 755 /usr/local/bin/redis-trib.rb

RUN tar -xzf /root/software/EP_mnmlstc_core.tar.gz  -C /root/build_software
WORKDIR /root/build_software/EP_mnmlstc_core/build
RUN cmake -DBUILD_TESTING=OFF  ..
RUN make -j4 && make install

RUN tar -xzf /root/software/mongo-c-driver-1.26.2.tar.gz -C /root/build_software
WORKDIR /root/build_software/mongo-c-driver-1.26.2/build
RUN cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .. && make  -j4 && make install

RUN tar -xzf /root/software/mongo-cxx-driver-r3.6.7.tar.gz -C /root/build_software
WORKDIR /root/build_software/mongo-cxx-driver-r3.6.7/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..  
RUN make -j4 && make install

RUN ldconfig

FROM debian:bullseye-20240311

ENV DEBIAN_FRONTEND noninteractive

# 改默认shell，选否
# make /bin/sh symlink to bash instead of dash:
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN dpkg-reconfigure dash
COPY --from=debian_tmp /usr /usr
COPY --from=debian_tmp /lib /lib
COPY --from=debian_tmp /lib64 /lib64
COPY --from=debian_tmp /etc /etc
COPY --from=debian_tmp /bin /bin
COPY --from=debian_tmp /sbin /sbin
RUN apt-get update
WORKDIR /root






